# Author : Loan BERNAT (l.bernat@sileane.com)

import rclpy
from rclpy.node import Node
from rclpy.action import ActionClient
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from control_msgs.action import FollowJointTrajectory
from control_msgs.srv import QueryTrajectoryState
from builtin_interfaces.msg import Duration
from rclpy.executors import MultiThreadedExecutor

import os
import sys

from hpp_interface.srv import HppSendTrajectory

from hpp.corbaserver import Client

from .utils import generateMessage

# ros2 service call /sendTrajectory hpp_interface/srv/HppSendTrajectory "{'path_id':3, 'derivative_indice':2}"

class HPPSend(Node):
    '''
    This node allows to send a trajectory generated by HPP to the ros2_control JointTrajectoryController.

    To use this node, you need to use a separated script containing all your HPP simulation.
    You just need to call from your script the service /hpp_node/sendTrajectory using the type HppTrajectory.srv

    You need to respect the HPP order for configuration [robot, robot_finger1, robot_finger2, obj1, obj2 ..]
    IMPORTANT : Currently, this script support only robot with 7 joints (+ 1 grip (optional))
    '''
    # These variables are changed dynamically in the code.
    q_goal = None
    q_init = None
    hpp_joint_names = None
    gripper_value = None

    SUPPORTED_ROBOTS = ['fer','fr3']

    def __init__(self):
        super().__init__('hpp_node')

        self.declare_parameter('arm_id', "")
        self.arm_id = self.get_parameter('arm_id').value

        self.declare_parameter('load_grip', False)
        self.no_grip = not self.get_parameter('load_grip').value

        if self.arm_id not in self.SUPPORTED_ROBOTS:
            raise RuntimeError(f"ERROR : Bad argument.\nRobot {self.arm_id} is not supported. Avalaible robots {self.SUPPORTED_ROBOTS}")
        
        # Send the trajectory to the controller
        self.controller = ActionClient(self, FollowJointTrajectory, 
                                   '/joint_trajectory_controller/follow_joint_trajectory')
        
        
        self.sending_service = self.create_service(HppSendTrajectory, 'hpp_node/sendTrajectory', self.send)

        # Receive the current config of the robot
        self.state_service = self.create_client(QueryTrajectoryState, '/joint_trajectory_controller/query_state')

    def send(self, request, response):

        response.sucess = False

        self.get_logger().info("Processing inputs")

        try:
            c = Client()
            derivative, pathID = request.derivative_indice, request.path_id
        except:
            self.get_logger().error("ERROR : Failed to connect to the hppcorbaserver")
            return response
        if derivative not in [0,1,2]:
            self.get_logger().error(f"ERROR : Bad derivative indice {derivative}.\n Must be 0,1 or 2")
            return response
        try:
            waypoints, times = c.problem.getWaypoints(pathID)
        except:
            self.get_logger().error(f"ERROR : Failed to find a path with the id : {pathID}")
            return response        

        trajectory_msg = FollowJointTrajectory.Goal()

        trajectory_msg.trajectory = generateMessage(c.problem,waypoints,times,derivative,pathID,self.arm_id,self.no_grip)

        self.controller.wait_for_server()
        goal_handle = self.controller.send_goal_async(trajectory_msg).result() #Implementer des suivis du feedback
        self.get_logger().info("Trajectory sended")

        response.sucess = True
        return response


def main(args=None):
    rclpy.init(args=args)

    hpp = HPPSend()
    executor = MultiThreadedExecutor()
    executor.add_node(hpp)
    executor.spin()

    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    hpp.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()




# self.ps.addOptimizer()







# print (ps.solve ())
# Pour recup la traj avec les points :  wp, times = ps.getWaypoints(pathId=0) times = [t1,t2,..ti..]
# POur trouver les vitesses ps.derivativeAtParam(pathId, 1, ti)

## Uncomment this to connect to a viewer server and play solution paths
# 
# v = vf.createViewer()
# from hpp.gepetto import PathPlayer
# pp = PathPlayer (v)

# pp (0)
# pp (1)

