# Author : Loan BERNAT (l.bernat@sileane.com)

import rclpy
from rclpy.node import Node
from rclpy.action import ActionClient
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from control_msgs.action import FollowJointTrajectory
from control_msgs.srv import QueryTrajectoryState
from builtin_interfaces.msg import Duration
from rclpy.executors import MultiThreadedExecutor

import os
import sys

from hpp_interface.srv import HppSendTrajectory

from hpp.corbaserver import Client

class HPPSend(Node):
    '''
    This node allows to send a trajectory generated by HPP to the ros2_control JointTrajectoryController.

    To use this node, you need to use a separated script containing all your HPP simulation.
    You just need to call from your script the service /sendTrajectory using the type HppTrajectory.srv

    You need to respect the HPP order for configuration [robot, robot_finger1, robot_finger2, obj1, obj2 ..]
    IMPORTANT : Currently, this script support only robot with 7 joints (+ 1 grip (optional))
    '''
    # These variables are changed dynamically in the code.
    q_goal = None
    q_init = None
    hpp_joint_names = None
    gripper_value = None

    SUPPORTED_ROBOTS = ['fer','fr3']

    def __init__(self):
        super().__init__('hpp_node')

        self.declare_parameter('arm_id', "fer")
        self.arm_id = self.get_parameter('arm_id').value

        self.declare_parameter('load_grip', False)
        self.no_grip = not self.get_parameter('load_grip').value

        if self.arm_id not in self.SUPPORTED_ROBOTS:
            raise RuntimeError(f"ERROR : Bad argument.\nRobot {self.arm_id} is not supported. Avalaible robots {self.SUPPORTED_ROBOTS}")
        
        # Send the trajectory to the controller
        self.controller = ActionClient(self, FollowJointTrajectory, 
                                   '/joint_trajectory_controller/follow_joint_trajectory')
        
        
        self.sending_service = self.create_service(HppSendTrajectory, '/sendTrajectory', self.send)

        # Receive the current config of the robot
        self.state_service = self.create_client(QueryTrajectoryState, '/joint_trajectory_controller/query_state')

    def send(self, request, response):

        # joint_request = QueryTrajectoryState.Request()
        # self.future_state = self.state_service.call_async(joint_request)

        response.sucess = False

        self.get_logger().info("Processing inputs")

        try:
            c = Client()
            derivative, pathID = request.derivative_indice, request.path_id
        except:
            self.get_logger().error("ERROR : Failed to connect to the hppcorbaserver")
            return response
        if derivative not in [0,1,2]:
            self.get_logger().error(f"ERROR : Bad derivative indice {derivative}.\n Must be 0,1 or 2")
            return response
        try:
            waypoints, times = c.problem.getWaypoints(pathID)
        except:
            self.get_logger().error(f"ERROR : Failed to find a path with the id : {pathID}")
            return response        

        trajectory_msg = FollowJointTrajectory.Goal()

        trajectory = JointTrajectory()
        trajectory.points = []

        

        l = len(times)
        for i in range(l):
            sys.stdout.write(f"\rCalculating derivative {i+1}/{l}")
            sys.stdout.flush()
            wp = waypoints[i]
            point = JointTrajectoryPoint()
            point.positions = self.extractRobotConfig(wp, grip=wp[7])
            if derivative == 0:
                v = [0.0 for e in range(len(point.positions))]
            else:
                v = c.problem.derivativeAtParam(0, derivative, times[i])
            point.velocities = self.extractRobotConfig(v)
            point.time_from_start = Duration(sec=int(times[i]), nanosec=int((times[i] - int(times[i])) * 1e9))

            trajectory.points.append(point)
        print()

        # if not self.future_state.done():  # Check if the service response has arrived
        #     self.get_logger().info("Waiting for joint names to arrive before sending trajectory...")
        #     rclpy.spin_until_future_complete(self, self.future_state)  # Block only if necessary

        # # Step 4: Extract the joint names from the service response
        # if self.future_state.result() is not None:
        #     trajectory.joint_names = self.future_state.result().joint_names
        #     self.get_logger().info(f"Received joint names: {trajectory.joint_names}")
        # else:
        #     self.get_logger().error("Failed to get joint names")
        #     return response

        trajectory.joint_names = [f'{self.arm_id}_joint1',f'{self.arm_id}_joint2',f'{self.arm_id}_joint3',f'{self.arm_id}_joint4',f'{self.arm_id}_joint5',f'{self.arm_id}_joint6',f'{self.arm_id}_joint7']
        if not self.no_grip:
            trajectory.joint_names.append(f'{self.arm_id}_finger_joint1')

        trajectory_msg.trajectory = trajectory

        self.controller.wait_for_server()
        goal_handle = self.controller.send_goal_async(trajectory_msg).result()
        self.get_logger().info("Trajectory sended")

        response.sucess = True
        return response


    # ==========================================================
    # Following function need to be modified to be more generalist

    def extractRobotConfig(self, q, grip=0.0): 
        # Le param grip permet de passer la valeur pour le joint gripper. 
        # En position on envoie la valeur orginale.
        # En vitesse 0, car le gripper est statique.

        q_ros2 = q[0:7]
        if not self.no_grip:
            q_ros2.append(grip)

        # tri selon les noms de joint
        # for q_name in desired_joint_names:
        #    if q_name in self.gripper_value:
        #        q_ros2.append(self.gripper_value[q_name])
        #        continue
        #    for j in range(len(self.hpp_joint_names)):
        #        if q_name == self.hpp_joint_names[j]:
        #            q_ros2.append(q[j])
        #            break

        return q_ros2
    
    # ==============================================================


def main(args=None):
    rclpy.init(args=args)

    hpp = HPPSend()
    executor = MultiThreadedExecutor()
    executor.add_node(hpp)
    executor.spin()

    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    hpp.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()




# self.ps.addOptimizer()







# print (ps.solve ())
# Pour recup la traj avec les points :  wp, times = ps.getWaypoints(pathId=0) times = [t1,t2,..ti..]
# POur trouver les vitesses ps.derivativeAtParam(pathId, 1, ti)

## Uncomment this to connect to a viewer server and play solution paths
# 
# v = vf.createViewer()
# from hpp.gepetto import PathPlayer
# pp = PathPlayer (v)

# pp (0)
# pp (1)

